"""Criação inicial das tabelas

Revision ID: 4a8f9c21eff6
Revises: 
Create Date: 2025-03-16 12:56:56.514901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8f9c21eff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('objeto_roubado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=50), nullable=False),
    sa.Column('transportadora', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=50), nullable=True),
    sa.Column('forma_subtracao', sa.String(length=100), nullable=True),
    sa.Column('meio_utilizado', sa.String(length=50), nullable=True),
    sa.Column('boletim_ocorrencia', sa.String(length=50), nullable=True),
    sa.Column('rua', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('data_ocorrencia', sa.Date(), nullable=False),
    sa.Column('hora_ocorrencia', sa.Time(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objeto_roubado')
    op.drop_table('usuario')
    # ### end Alembic commands ###
